/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.flipperplz.dztools_wrapper

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
    }
}
